[project]
name = "screenshot-pixel-color-print"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=10.0.0",
    "colorspacious>=1.1.2",
]
